### PR TITLE
Rebuild for Python 3.7, GCC 7, R 3.5.1, openBLAS 0.3.2

### PR DESCRIPTION
**Pull request by xhochy**
Fixes #6

### CODE REVIEW

**Comment by xhochy** [comment]
leveldb-feedstock needs to be migrated first.

**Comment by xhochy** [comment]
@conda-forge-admin please rerender

**Comment by xhochy** [comment]
Seems like this only works with leveldb=1.18

**Comment by xhochy** [comment]
Depends on https://github.com/conda-forge/leveldb-feedstock/pull/10

**Comment by xhochy** [comment]
@conda-forge-admin please rerender

**Comment by xhochy** [comment]
@conda-forge-admin please rerender

**Comment by xhochy** [comment]
@conda-forge/python-leveldb This is ready for review/merge.

**Comment by xhochy** [comment]
@conda-forge/python-leveldb This is ready for review/merge.

**Comment by sdvillal** [comment]
LGTM

**Pull request merged**
